{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Server", "query": "SELECT [Name] FROM SQLServers" }
  ]
 },
 "panels": [
  {
   "title": "Reliability",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Performance",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "$Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "Server" },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED\n SELECT $__timeEpoch([Timestamp]), [value] as value, 'CPU Utilization %' as metric FROM  [MetricValue_ServerMetrics] A WHERE metric = 'cpu usage' AND $__timeFilter([Timestamp]) AND server_name = $Server ORDER BY [Timestamp] ASC"
    }
   ]
  },
  {
   "title": "Page Life Expectancy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Timestamp),\n  CAST([Value] AS INT) as value,\n  'Page Life Expectancy' as metric\nFROM MetricValue_ServerMetrics \nWHERE    metric = 'Page life expectancy'\nAND server_name = $Server\nAND $__timeFilter(Timestamp)\n\n\n"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH latest_agent AS (SELECT MAX([timestamp]) [timestamp] FROM [MetricValue_ServerAgent] WHERE server_name = $Server), latest_metrics AS (SELECT DISTINCT MAX([timestamp]) [timestamp] FROM [MetricValue_ServerAgent] WHERE server_name = $Server) select 'Failed jobs' as Metric, count(DISTINCT job_name) as Value FROM [MetricValue_ServerAgent] A INNER JOIN latest_agent ON latest_agent.[timestamp] = A.[timestamp] WHERE [run_status] = 1 and run_datetime > DATEADD(day, -1, GETDATE()) and A.server_name = $Server UNION ALL SELECT 'Alerts' as Metric, Value FROM [MetricValue_ServerMetrics] B INNER JOIN latest_metrics ON latest_metrics.[timestamp] = B.[timestamp] where Metric = 'Alerts Count' and b.server_name = $Server"
    }
   ]
  }
 ]
}